### ISSUE TITLE
Create database models

### ISSUE THREAD

**Issue by karoliina** [karoliina/COMP4770#8]
The following database models need to be created (likely an incomplete list at this point):

  * ~~FriendRequest~~
  * ~~Group~~
  * GroupRequest
  * GroupInvitation
  * Notification
  * ~~GroupMembership~~
  * GroupPost
  * TimelinePost
  * LostAndFoundPost
  * Poll
  * ChatbotQuestion
  * Schedule
  * Course

**Comment by Nathan-J-Fowlow** [comment]
Currently looking at the following

1. Post /Comment(Group Post, Timeline Post, Lost & Found post)

2. Visibility (only me, public, only friends, custom {list of specified friends})

**Comment by karoliina** [comment]
I'm working on the server side implementation of creating and joining groups, and dealing with all kinds of requests and notifications. Going to write both the database models and the controllers for these, hopefully some tests soon too.

For notifications, I think I'll use [Mongoose Discriminators](http://mongoosejs.com/docs/discriminators.html), which is kind of an inheritance pattern for Mongoose. This will make it possible to retrieve all of a user's notifications with a single query. If it works out well, I may switch the requests to use discriminators too.
